source 'https://rubygems.org'

platforms :ruby do
  gem 'json'
end

platforms :jruby do
  gem 'jruby-json'
end

group :development do
  # Ruby 1.9 specific (debug/profiling) gems
  gem 'rspec'
  gem 'pry'
end